apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
  namespace: to-do
  labels:
    project: to-do-list
    component: backend
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      project: to-do-list
      component: backend
  template:
    metadata:
      labels:
        project: to-do-list
        component: backend
    spec:
      containers:
        - name: be
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: be-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: be-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: be-config
                  key: DB_NAME