apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-deployment
  namespace: to-do
  labels:
    project: to-do-list
    component: database
spec:
  serviceName: mysql-headless
  replicas: 1
  selector:
    matchLabels:
      project: to-do-list
      component: database
  template:
    metadata:
      labels:
        project: to-do-list
        component: database
    spec:
      containers:
        - name: db
          image: mysql:8.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_USER

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: todo
        resources:
          requests:
            storage: 10Gi