apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: to-do-list-stage
    region: us-east-1
managedNodeGroups:
  - name: to-do-list-stage 
    instanceType: "t3.micro"
    desiredCapacity: 3 #  by default this value is 3