apiVerion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  namespace: to-do
  labels:
    project: to-do-list
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      project: to-do-list
      component: frontend
  template:
    metadata:
      labels:
        project: to-do-list
        component: frontend
    spec:
      containers:
        - name: fe
          image: pavithrakasukurthi/fe:v1
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: to-do
spec:
  type: LoadBalancer
  selector:
      project: to-do
      component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    