pipeline {
    agent {
        node {
            label 'Linux'
        }
    }

    options {
        timeout(time: 60, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    stages {
        stage('Deploy') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                        set -e
                        aws eks update-kubeconfig --region us-east-1 --name roboshop-stage
                        kubectl get nodes
                        kubectl create namespace to-do || true
                        helm upgrade --install be -n to-do --atomic --wait --timeout=5m ./helm/be
                        """
                    }
                }
            }
        }
         stage('Trigger Frontend Deploy') {
            steps {
                build job: 'fe-deploy', wait: false
            }
        }
    }
}