apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: to-do
spec:
  type: LoadBalancer
  selector:
      project: to-do-list
      component: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80